defaults: &defaults
  working_directory: ~/upload_flush_list_mt
  shell: /bin/bash --login
  environment:
    CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    SBT_JUNIT_DIR: /tmp/circleci-test-results/sbt
    JVM_OPTS: -Xmx3200m
    TERM: dumb
  docker:
    - image: andyg42/generic-centos-sbt:4

version: 2
jobs:
  build_and_test:
    <<: *defaults
    steps:
    - setup_remote_docker
    - checkout
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ checksum "build.sbt" }}
        # Default branch if not
        - v1-dep-{{ .Branch }}-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1-dep-
    - run: cat /dev/null | sbt test:compile
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.ivy2
        - ~/.m2
        - target
    - run: cat /dev/null | sbt test
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results

    ### deployment
    - run: cat /dev/null | sbt rpm:packageBin
    - run: aws s3 cp target/rpm/RPMS/noarch/mrpushy-1.0.0-${CIRCLE_BUILD_NUM}.noarch.rpm s3://gnm-multimedia-deployables/upload_flush_list/${CIRCLE_BUILD_NUM}/mrpushy.noarch.rpm
    - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWD} && echo exit | sbt -Dbuild.number=${CIRCLE_BUILD_NUM} -Ddocker.username=guardianmultimedia docker:publish
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test